### ISSUE TITLE
Proposal: Shell file full of useful helper functions

### ISSUE THREAD

**Issue by jchauncey** [deis/docker-base#5]
I find myself right now wishing I had a `wait-for-pod` function that I could call and let me boot script wait until another pod was up and ready. Crash looping basically requires very similar logic and in this case I could have a timeout where I crash after x amount of time or retries. 

There are definitely other functions I'd like to see (curling the kube api for instance) so was wondering what other people thought about this?

I also want to add envtpl to the base image since I am basically using it in every monitoring and logging image and its pretty darn useful.

**Comment by bacongobbler** [comment]
Is this still something you desire? IMO since envtpl seems like a logger/monitor specific tool perhaps that should only exist in downstream images, but handy helper binaries like `wait-for-pod` could potentially be incredibly useful across all components.

At the same time I'd prefer us to prevent kube-specific callouts in our code wherever possible such that the container becomes more portable, but I understand that sometimes that's just not an option (the router, for example).

**Comment by bacongobbler** [comment]
ping

**Comment by jchauncey** [comment]
we can close this
